development:
   adapter: mysql2
   encoding: utf8
   database: blog_development
   pool: 5
   username: root
   password: root
   socket: /tmp/mysql.sock
production:
  adapter: postgresql
  encoding: unicode
  database: blog_production
  pool: 5
  username: root
  password:  root